export const htmlToDom = {
  class: "className",
  accesskey: "accessKey",
  autocapitalize: "autoCapitalize",
  contenteditable: "contentEditable",
  contextmenu: "contextMenu",
  playsinline: "playsInline",
  spellcheck: "spellCheck",
  tabindex: "tabIndex",
  noshade: "noShade",
  hreflang: "hrefLang",
  referrerpolicy: "referrerPolicy",
  datetime: "dateTime",
  autoplay: "autoPlay",
  crossorigin: "crossOrigin",
  ismap: "isMap",
  usemap: "useMap",
  srclang: "srcLang",
  allowfullscreen: "allowFullScreen",
  allowpaymentrequest: "allowPaymentRequest",
  srcdoc: "srcDoc",
  colspan: "colSpan",
  rowspan: "rowSpan",
  autofocus: "autoFocus",
  formaction: "formAction",
  formenctype: "formEncType",
  formmethod: "formMethod",
  formnovalidate: "formNoValidate",
  formtarget: "formTarget",
  acceptcharset: "acceptCharset",
  autocomplete: "autoComplete",
  novalidate: "noValidate",
  dirname: "dirName",
  maxlength: "maxLength",
  readonly: "readOnly",
  minlength: "minLength",
};

export const toggleableAttributes = [
  "contenteditable",
  "autofocus",
  "autoplay",
  "allowfullscreen",
  "allowpaymentreques",
  "checked",
  "controls",
  "compact",
  "disabled",
  "hidden",
  "ismap",
  "loop",
  "multiple",
  "muted",
  "open",
  "playsinline",
  "readonly",
  "required",
  "selected",
  "async",
  "defer",
];
